guake &
sleep 5
guake -r "VPN Tunnel" --execute-command='./TUNNEL'
guake -n k -r "jhartmann-desktop 1" --execute-command='./sshjh'
guake -n k -r "jhartmann-desktop 2" --execute-command='./sshjh'
guake -n k -r "inara 1" --execute-command='./sshjh'
guake -n k -r "inara 2" --execute-command='./sshjh'
guake -n k -r "User #1" --execute-command='cd ~'
guake -n k -r "User #2" --execute-command='cd ~'
guake -n k -r "User #3" --execute-command='cd ~'
guake -n k -r "SQL*Plus" --execute-command='cd ~/1Projects/current/erx-build/dist/database/db/OLTP/trexone_proxy/Deltas'
guake -n k -r "Test" --execute-command='cd ~/1Projects/current/Test'
guake -n k -r "Build" --execute-command='cd ~/1Projects/current'
guake -n k -r "Atlanta #1" --execute-command='cd ~'
guake -n k -r "Atlanta #2" --execute-command='cd ~'
guake -n k -r "Pgh #1" --execute-command='cd ~'
guake -n k -r "Pgh #2" --execute-command='cd ~'
guake -n k -r "GIT" --execute-command='cd ~'
